{{- if eq .Values.expose.type "ingress" }}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 128k
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
  name: {{ include "common.names.fullname" . }}
spec:
  rules:
  - host: {{ .Values.expose.hosts | quote}}
    http:
      paths:
      - path: /
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" 80 "context" $) | nindent 10 }}
      - path: /api/
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.console.defaultName" .) "servicePort" 8889 "context" $) | nindent 10 }}
      - path: /v2/
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.scanner.dockerregistry.defaultName" .) "servicePort" 5000 "context" $) | nindent 10 }}
      - path: /openapi/
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.console.defaultName" .) "servicePort" 8889 "context" $) | nindent 10 }} 
      - path: /internal/
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.console.defaultName" .) "servicePort" 8889 "context" $) | nindent 10 }}
      - path: /api/v1/vulns/updata
        {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.scanner.defaultName" .) "servicePort" 8888 "context" $) | nindent 10 }}    
  {{- if .Values.expose.tls.enable }}
  tls:
  - hosts:
    - {{ .Values.expose.hosts }}
    secretName: ingress-tls
  {{- end }}
{{- end }}
