{{- if eq .Values.expose.type "ingress" }}
{{- if .Values.expose.tls.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls 
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certfile/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "certfile/tls.key" | b64enc | quote }}
{{- end }}
{{- end }}
