apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  {{- if eq .Values.expose.type "NodePort" }}
  type: NodePort 
  {{- else }}
  type: ClusterIP 
  {{- end }}
